/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.container[_ngcontent-%COMP%]{\n    width: 50%;\n    background-color: #797773;\n    padding: 30px;\n}\nform[_ngcontent-%COMP%]{\n    display: flex;\n}\nform[_ngcontent-%COMP%]   input[_ngcontent-%COMP%]{\n    width: 100%;\n    margin: 0 10px;\n}\n.list-area[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]{\n    list-style: none;    \n}\n\nli[_ngcontent-%COMP%]{\n    background-color: #b9b2a9;\n    width: 80%;\n    padding: 5px;\n    border-radius: 10px;\n    margin: 10px 0px;\n    display: flex;\n    justify-content: space-around;\n}\n\nli[_ngcontent-%COMP%]   div[_ngcontent-%COMP%]   span[_ngcontent-%COMP%]{\n    font-size: 20px;\n    color: white;   \n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWFkaGF2L1dlYiBQcm9qZWN0cy9BT1QgUE9DL2FvdC1wb2Mvc3JjL2FwcC9hcHAuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL21hZGhhdi9XZWIgUHJvamVjdHMvQU9UIFBPQy9hb3QtcG9jL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
